### ISSUE TITLE
Add Danger for PR automation

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [5AbhishekSaxena/print-me-android#11]
Reference: [https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly](https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly)

Steps to add Danger.

1. Add github action to perform danger check on the PR. (`.github/workflows/danger_checks.yml`)
```yml
name: Danger Checks

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set Up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Danger Checks
        run: |
          gem install bundler
          bundle install
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
2. Create a `Dangerfile` in the root directory.
```
message "Thanks @#{github.pr_author}!"

if github.pr_body.length == 0
    fail "Please provide a summary in the Pull Request description."
end

if git.lines_of_code > 500
    warn "Please consider breaking up this pull request."
end

if github.pr_labels.empty?
    warn "Please add labels to this PR."
end

if git.deletions > git.insertions
    message  "🎉 Code Cleanup!"
end
```
3. Create a `Gemfile` in the root directory.
```
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "danger"
```

**Optional**
You can also print out the list of outdated dependencies on the PR with the help of danger.

Steps to add dependency version check plugin by  Ben Manes: [https://github.com/ben-manes/gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin)

1. Add the plugin to the project `build.gradle`
```gradle
plugins {
    id "com.github.ben-manes.versions" version "$versionsPluginVersion" // 0.29.0
}
```
2. Create a buildscript for versions plugin `buildscripts/versionsplugin.gradle` and enter the configuration for versions plugin.
```gradle
apply plugin: "com.github.ben-manes.versions"

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }

    gradleReleaseChannel = "current"
}
```
3. Add the versions plugin script to project level build.gradle file.
```gradle 
subprojects {
    .... // other gradle scripts
    apply from: "../buildscripts/versionsplugin.gradle"
}
```
4.  Test the plugin using `./gradlew dependencyUpdates`.
5. (Optional) Add the task to the github action - danger check.
   i. Add the following lines to the `Dangerfile` to print the output of `./gradlew dependencyUpdates`
```gradle
# Notify of outdated dependencies
dependencyReportsFile = "app/build/dependencyUpdates/report.txt"
dependencyUpdatesHeader = "The following dependencies have later milestone versions:"

hasDependencyUpdatesHeader = File.readlines(dependencyReportsFile).grep(/#{dependencyUpdatesHeader}/).any?

if hasDependencyUpdatesHeader
    file = File.open(dependencyReportsFile, "rb").read
    index = file.index(dependencyUpdatesHeader)
    message file.slice(index..-1)
end
```
   ii. Execute the task in the github actions - Danger Checks
```yml
name: Danger Checks

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set Up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Change wrapper permissions // new
        run: chmod +x ./gradlew

      - name: Danger Checks
        run: |
          ./gradlew dependencyUpdates // new
          gem install bundler
          bundle install
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

#### Tip/Recommendation
Move all the dependency versions to a centralized location.

Steps to centralize dependency versions.
1. Create a `buildsripts/versions.gradle` file for module dependencies(example: app/build.gradle)
```gradle
ext { // don't forget this ext otherwise it won't work
    versions = [
            // implementation

            // https://developer.android.com/jetpack/androidx/releases/core
            ktxCore                : "1.7.0",
            // https://developer.android.com/jetpack/androidx/releases/lifecycle
            lifeycle               : "2.4.1",


            // testing

            // https://developer.android.com/jetpack/androidx/releases/test
            androidxTestJunit      : "1.1.3",
            // https://developer.android.com/jetpack/androidx/releases/test
            espresso               : "3.4.0",
            // https://github.com/junit-team/junit4/releases
            junit                  : "4.13.2",

    ]
}
```
2. Refer to the versions in the module as follows. (app/build.gradle)
```gradle
dependencies {

    implementation "androidx.core:core-ktx:$rootProject.ext.versions.ktxCore"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$rootProject.ext.versions.lifeycle"

    testImplementation "junit:junit:$rootProject.ext.versions.junit"
    androidTestImplementation "androidx.test.ext:junit:$rootProject.ext.versions.androidxTestJunit"
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.ext.versions.espresso"
}
```
3. Put together the dependency versions in the project level `build.gradle` file together.
```gradle
buildscript {
    ext {
       // URL for the github releases 
        kotlinVersion = '1.6.10'
       
       .... // other versions
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
```
4. Refer to the versions in the project level gradle file as follows.
```gradle
plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version "$kotlinVersion" apply false

   .... // other plugins
}
```
5. Apply the `versions.gradle` to the project level `build.gradle` file.
```gradle
buildscript {
    ext {
        .... // project level gradle file dependency versions.
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    .... // plugins
}

apply from: "buildscripts/versions.gradle" // added here

subprojects {
    .... // subproject gradle scripts
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by 5AbhishekSaxena** [comment]
Complete project `build.gradle` file.

```gradle
buildscript {
    ext {
        .... // other versions
        // https://github.com/ben-manes/gradle-versions-plugin
        versionsPluginVersion = "0.29.0"
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    .... // other plugins
    id "com.github.ben-manes.versions" version "$versionsPluginVersion"
}

apply from: "buildscripts/versions.gradle"

subprojects {
    .... // other buildsccripts
    apply from: "../buildscripts/versionsplugin.gradle"
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by 5AbhishekSaxena** [comment]
Complete `Dangerfile`.

```
message "Thanks @#{github.pr_author}!"

if github.pr_body.length == 0
    fail "Please provide a summary in the Pull Request description."
end

if git.lines_of_code > 500
    warn "Please consider breaking up this pull request."
end

if github.pr_labels.empty?
    warn "Please add labels to this PR."
end

if git.deletions > git.insertions
    message  "🎉 Code Cleanup!"
end

# Notify of outdated dependencies
dependencyReportsFile = "app/build/dependencyUpdates/report.txt"
dependencyUpdatesHeader = "The following dependencies have later milestone versions:"

hasDependencyUpdatesHeader = File.readlines(dependencyReportsFile).grep(/#{dependencyUpdatesHeader}/).any?

if hasDependencyUpdatesHeader
    file = File.open(dependencyReportsFile, "rb").read
    index = file.index(dependencyUpdatesHeader)
    message file.slice(index..-1)
end
```

**Comment by 5AbhishekSaxena** [comment]
Complete `Danger Check` workflow(Github Action).

```yml
name: Danger Checks

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set Up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Danger Checks
        run: |
          ./gradlew dependencyUpdates
          gem install bundler
          bundle install
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
