### ISSUE TITLE
Add Detekt for code smell checks.

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [5AbhishekSaxena/print-me-android#15]
Reference: [https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly](https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly)

Steps to integrate Detekt

1. Add detekt pluigin in project level `build.gradle`.
  ```gradle
plugins {
     ...
      id 'io.gitlab.arturbosch.detekt' version "$detektVersion" // 1.19.0-RC2
 }
  ```
2. Create a buildscript for detekt as `buildscripts/detekt.gradle` and enter the configuraton for deket plugin.
```gradle
apply plugin: "io.gitlab.arturbosch.detekt"

detekt {
    config = files("${rootProject.projectDir}/config/detekt/detekt.yml")

    reports {
        html.enabled = true
        xml.enabled = true
        txt.enabled = true
    }
}
```
3.  Add the detekt script to project level `build.gradle` file.
```gradle
subprojects {
   ...
    apply from: "../buildscripts/detekt.gradle"
}
```
4. Execute gradle task `<ProjectName>Tasks>verification>detektGenerateConfig`
or `./gradlew detektGenerateConfig` to generate the default detekt configuration.
5. Update configuration for Jetpack Compose. (`config/detekt/detekkt.yml`)
Reference: [https://detekt.dev/docs/introduction/compose/](https://detekt.dev/docs/introduction/compose/).

Add additional configurations
```yml
style:
   UnusedPrivateMember:
        ... // other properties
        ignoreAnnotated: ['Preview']
   MagicNumber:
       ... // other properties
        ignoreAnnotated: ['Preview']

naming:
    FunctionNaming:
        ... // other properties
        ignoreAnnotated: ['Composable']  // new
```

In `Color.kt` add `@file:Suppress("MagicNumber")` on the top the file.

For Hilt,

```yml
style:
  UnnecessaryAbstractClass:
    ... // other properties
    ignoreAnnotated: ['Module'] // new
```

Optional
- Add `@Suppress("UnusedPrivateMember", "MagicNumber")` to Composae Previews.
