### ISSUE TITLE
Add Github Actions workflow for Android Build and Android UI Tests.

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [5AbhishekSaxena/print-me-android#17]
Reference: [https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly](https://www.youtube.com/watch?v=ePpbpLyYI1w&list=PLeJI6UYqZX0IL4nSYTVY1-qE-VFn3SLk-&index=4&ab_channel=AdamMcNeilly)

#### Pro Tip
Use the Github website to create/edit Github Actions, it comes with a great UI and even better autocomplete.

Steps to add github actions.
1. Create a directory for github actions as `.github/workflows/`.
2. Add `.github/workflows/android_build.yml`
```yml
name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test
```
3. Add `.github/workflows/android_ui_test.yml`
```yml
name: Android UI Tests

on: pull_request

jobs:
  android-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Change wrapper persmissions
        run: chmod +x ./gradlew

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew app:connectedCheck
```
